name: CD

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: self-hosted
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      
      - name: Set up Node
        uses: actions/setup-node@v2
        id: cache
        with:
          node-version: '14'
          cache: 'npm'
          cache-dependency-path: '**/client/package-lock.json'
          
      - name: Create .env file    
        run: |
          touch .env
          echo PORT=5000 >> .env
          echo DB_PASSWORD=${{ secrets.DB_PASSWORD }} >> .env
          cat .env
          
      - name: Install node dependencies
        run: npm install
      
      - name: Install react dependencies
        if: steps.cache.outputs.cache-hit != 'true'
        run: |
          cd client
          npm install
        
      - name: Build  
        run: npm run build
