name: CD

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: self-hosted
    
    strategy:
      matrix:
        node-version: [14.x]
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      
      - name: Set up Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
          
      - name: Create .env file    
        run: |
          touch .env
          echo PORT=5000 >> .env
          echo DB_PASSWORD=${{ secrets.DB_PASSWORD }} >> .env
          cat .env
          
      - name: Cache node modules
        uses: actions/cache@v2
        env:
          cache-name: cache-node-modules
        with:
          path: ~/.npm
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
          
      - name: Install node dependencies    
        run: npm install
      
      - name: Install client dependencies
        run: npm install
        working-directory: client
        
      - name: Build  
        run: npm run build
