name: CD

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: self-hosted
    
    steps:
      - uses: actions/checkout@v2      
      
      - name: Set up Node
        uses: actions/setup-node@v2
        with:
          node-version: '14'
                    
      - name: Create .env file    
        run: |
          touch .env
          echo PORT=5000 >> .env
          echo DB_PASSWORD=${{ secrets.DB_PASSWORD }} >> .env
          echo MAPS_API_KEY=${{ secrets.MAPS_API_KEY }} >> .env
          echo MAPS_SERVER_API_KEY=${{ secrets.MAPS_SERVER_API_KEY }} >> .env
          cat .env
          
      - name: Install node dependencies
        run: npm install
      
      - name: Install react dependencies
        run: |
          cd client
          npm install
        
      - name: Build  
        run: npm run build
      
      - name: Restart pm2
        run: |
          pm2 stop 0
          pm2 start 0
          pm2 save

