name: CD

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 14
      - uses: SpicyPizza/create-envfile@v1
        with:
          envkey_PORT: 5000
          envkey_SECRET_KEY: ${{ secrets.DB_PASSWORD }}
          file_name: .env
      - run: npm ci
      - run: npm ci
        working-directory: client
      - run: npm run build
