name: CI

on:
  pull_request:
    branches: [ main ]

  workflow_dispatch:

jobs: 
  test_pull_request:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with: 
          node-version: 14
      - run: npm install
      - run: npm install
        working-directory: client
      - run: npm test
      - run: CI= npm run build

