name: CI

on:
  pull_request:
    branches: [ main ]

  workflow_dispatch:

jobs: 
  test_pull_request:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: setup-node@v1
        with: 
          node-version: 14
      - run: npm ci
      - run: npm test
      - run: npm run build
